### ISSUE TITLE
Folder navigation buttons intersect with OAuth mod GUI

### ISSUE THREAD

**Issue by Kikugie** [kevinthegreat1/OrganizablePlayScreens-Fabric#1]
![image](https://user-images.githubusercontent.com/50152507/194757721-3863532d-6d16-4bd4-b245-728351512961.png)
Idk if its possible to detect if that space is already occupied, but alternatively config for button location would work.

**Comment by kevinthegreat1** [comment]
I'll probably add config at some point.

**Comment by kevinthegreat1** [comment]
Options are added in version 1.1.0. Please report any bugs! Thanks for the idea.
