### ISSUE TITLE
The game crashes when you press the 'Done' button in a server editing screen

### ISSUE THREAD

**Issue by CommandLeo** [kevinthegreat1/OrganizablePlayScreens-Fabric#10]
The game crashes when you press the 'Done' button in a server editing screen. Crash report link: https://mclo.gs/i2qgUWn

# How to reproduce:
- Create a 1.20.1 instance with Fabric API and Organizable Play Screens
- Launch the game and go to the multiplayer menu
- Add a server to the list
- Select the server and click the 'Edit' button
- Click on 'Done'

**Comment by kevinthegreat1** [comment]
Fixed in 980c833
