### ISSUE TITLE
[Bug] Game crashes when modifying a server

### ISSUE THREAD

**Issue by Finoway** [kevinthegreat1/OrganizablePlayScreens-Fabric#11]
Hello,

I just downloaded the mod on modrinth and when I modify a server the game crashes. I know that there has already been an issue about this and that normally it is fixed but in my case not. (https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/issues/10)

Here's a video to show the bug: https://youtu.be/9DQX-GcMA0w
Here's the crash report: [crash-2023-07-25_22.56.48-client.txt](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/files/12165567/crash-2023-07-25_22.56.48-client.txt)

**Comment by Finoway** [comment]
I just realized the date of the commit and the release date, I hadn't seen them. I'd love to have the fix commit on modrinth x)

**Comment by kevinthegreat1** [comment]
I’ll release the new version soon. Meanwhile, you can use the build [here](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/suites/14199213122/artifacts/796419953).

**Comment by Finoway** [comment]
> I’ll release the new version soon. Meanwhile, you can get the build [here](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/suites/14199213122/artifacts/796419953).

Yes I know it's just that I had not watched that the version of modrinth did not have the patch I have already get it, thank you for the information ^^
