### ISSUE TITLE
1.20.4 support

### ISSUE THREAD

**Issue by ancap-kun** [kevinthegreat1/OrganizablePlayScreens-Fabric#14]

**Comment by ancap-kun** [comment]
Just saw 1.20.4 support commit. Maybe release it on modrinth?

**Comment by kevinthegreat1** [comment]
I'll release it once essential updates so I can test essential compatibility.

**Comment by ancap-kun** [comment]
Do you really think about compatibility with mod that does nothing except for turning minecraft into roblox with such bullshit as paid cosmetics?
