### ISSUE TITLE
just seems to crash in 1.20.5 no matter what

### ISSUE THREAD

**Issue by SnowyBoi64** [kevinthegreat1/OrganizablePlayScreens-Fabric#15]

**Comment by SnowyBoi64** [comment]
i cant really provide much more than that
maybe its built for an older fabric version or something?

**Comment by kevinthegreat1** [comment]
It works perfectly fine. I will need your logs to figure out what's wrong.
<img width="966" alt="Screenshot 2024-05-18 at 15 18 33" src="https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/assets/92656833/20b777c1-33ae-486f-9c63-cef180f92d48">

**Comment by SnowyBoi64** [comment]
oh oh ill send you them

[crash-2024-05-18_14.21.29-client.txt](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/files/15366572/crash-2024-05-18_14.21.29-client.txt)

**Comment by kevinthegreat1** [comment]
You need to download [modmenu](https://modrinth.com/mod/modmenu).

**Comment by SnowyBoi64** [comment]
Thanks I guess I didn’t see it there in the dependencies sorry for not checking there first
