### ISSUE TITLE
Game crashes when deleting or saving a world after editing

### ISSUE THREAD

**Issue by TQNL** [kevinthegreat1/OrganizablePlayScreens-Fabric#16]
How to reproduce this bug:
Create a 1.20.1 instance with Fabric API and Organizable Play Screens
Launch the game and go to the singleplayer menu
Select a world and click the 'Edit' button and Click on 'Save', press delete on a world

maybe there are more such bugs with button presses, idk

[crash-2024-07-05_15.10.55-client.txt](https://github.com/user-attachments/files/16110215/crash-2024-07-05_15.10.55-client.txt)

**Comment by kevinthegreat1** [comment]
Fixed in 1.2.4.
