### ISSUE TITLE
[Compatibility]: Button Overlap w/ Auth Me

### ISSUE THREAD

**Issue by Brittank88** [kevinthegreat1/OrganizablePlayScreens-Fabric#3]
Seems very similar to #1, so I assume that generally speaking there needs to be compat for all the re-authentication-type mods out there.

See:
![image](https://user-images.githubusercontent.com/24266948/198769759-6f30e306-f0d0-4a44-af6b-93df06543e2b.png)

**Comment by kevinthegreat1** [comment]
Yes, I think the best fix is configurable button location. I will try to add it soon. Thanks for reporting.

**Comment by kevinthegreat1** [comment]
Options are added in version 1.1.0. Please check it out and report any bugs! Thanks for the help.
