### ISSUE TITLE
Can't move worlds from experimental versions

### ISSUE THREAD

**Issue by Felix14-v2** [kevinthegreat1/OrganizablePlayScreens-Fabric#6]
You just can't select them
https://user-images.githubusercontent.com/75726196/224120845-6a7dda0f-d5c4-4d48-8bfd-94237610e3c5.mp4

Example world:
[(1.18) New world (experimental).zip](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/files/10934843/1.18.New.world.experimental.zip)

**Comment by kevinthegreat1** [comment]
This is vanilla behavior. However, this breaks folders so I added the ability to select unavailable worlds in the newest release. You can get it on [github](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/releases/tag/1.1.2), [modrinth](https://modrinth.com/mod/organizable-play-screens/version/1.1.2), or [cursedforge](https://www.curseforge.com/minecraft/mc-mods/organizable-play-screens/files/4430104).
