### ISSUE TITLE
Titles/Seperators (Suggestion)

### ISSUE THREAD

**Issue by TeggolT** [kevinthegreat1/OrganizablePlayScreens-Fabric#8]
- Add a new "server type" called title which can be named but not played. Maybe increase font size and remove Icon. Users can now add Titles to their servers.
- Add a new "server type" called separator which is basically just a title consisting of lines: --------------------------------------

Example structure:
title: Private Servers
 my own server
 my other own server
 seperator: --------------
 my friend's server
 another Friend's server
 seperator: --------------
 localhost server for testing
title: public servers
 Hypixel
 Mineplex
folder: Play With Friends
folder: Cool SMP's

Yes, you could organize these 9 servers with folders, but That'd mean a lot of clicking and really be just a timewaster. In comparison, a title or separator would clean things up without adding unnecessary clicks (or for my little modpack i play with friends, they don't want too unnecessary stuff in there but it's just too much servers).

**Comment by kevinthegreat1** [comment]
I like these ideas, and they shouldn't be too hard to implement. I will add them soon.  

P.S. Sorry for the late response, somehow I missed this.

**Comment by kevinthegreat1** [comment]
There is a test build you can try out [here](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/actions/runs/5482118094). You can download and unzip the artifacts at the bottom and drag the jar that doesn't end in sources to your mods folder.

**Comment by TeggolT** [comment]
Works great😃! I like that it doesn't add clutter to the original Interface, hiding the options behind the original +. 1.20 works fine too.
