### ISSUE TITLE
1.20+ ?

### ISSUE THREAD

**Issue by SkyWors** [kevinthegreat1/OrganizablePlayScreens-Fabric#9]
Hey!

It's a really good mod! When will it be available for versions 1.20 and above?

**Comment by kevinthegreat1** [comment]
Thanks! The mod will be updated in a few days.

**Comment by kevinthegreat1** [comment]
Sorry for the delay, I'm almost there.
<img width="445" alt="Screenshot 2023-07-06 at 20 38 05" src="https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/assets/92656833/ef220908-605c-4d0c-9a59-5a721054cfcd">

**Comment by SkyWors** [comment]
Hey !

There are absolutely no problems for the delay! Thanks again :smile:

**Comment by kevinthegreat1** [comment]
There is a test build you can try out [here](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/actions/runs/5482118094). You can download and unzip the artifacts at the bottom and drag that jar that doesn't end in sources to your mods folder.

**Comment by SkyWors** [comment]
Hey !

I had already compiled it in the first commit 1.20. This new version works perfectly fine except for one thing: it overwrites the existing organizable_servers.dat file, unlike the older versions of the mods.

**Comment by kevinthegreat1** [comment]
I tested on the newest version and the folders load correctly. Can you provide more details on what you are experiencing?

**Comment by SkyWors** [comment]
Of course,

1. I put the new mod in my mod's folder (i replaced the old one) - In this instance, I already have some server in folders.
2. I started the game,
3. And when i go in multiplayer screen, nothing loaded, not a single server.
4. I go back in the main menu,
5. And again in the multiplayer screen where all my server appeared but with no folders.

When i checked the organizable_servers.dat, I saw that he had been rewrite.
To be sure, I take an old save of this file and the same thing append.

**Comment by kevinthegreat1** [comment]
Does that happen with [the newest version](https://github.com/kevinthegreat1/OrganizablePlayScreens-Fabric/actions/runs/5482118094) (same as linked above)? I am unable to reproduce the issue. If you're still having the problem, please send your `latest.log` in the `logs` folder in your Minecraft directory.

**Comment by SkyWors** [comment]
Surprisingly, I can't reproduce the bug, so I'll assume that I've had an external source problem.

**Comment by kevinthegreat1** [comment]
This problem might have existed in older commits. 1.20 version of this mod is now published on modrinth, github, and curseforge. Thanks for your help.
